[package]
name = "termshell"
version = "0.1.0"
authors = ["Mihail Kovachev <bionic404.notfound@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
